blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'

urlpatterns = [
    url(r'^$', views.PostListView.as_view(), name='index'),
    url(r'^category/(?P<slug>[^\.]+)/$', views.CategoryListView.as_view(), name='category'),
    url(r'^post/add/$', views.PostCreateView.as_view(), name='post-add'),
    url(r'^post/(?P<slug>[^\.]+)/edit/$', views.PostEditView.as_view(), name='post-edit'),
    url(r'^post/(?P<slug>[^\.]+)/delete/$', views.PostDeleteView.as_view(), name='post-delete'),
    url(r'^post/(?P<slug>[^\.]+)/$', views.PostDetailView.as_view(), name='post'),
]

vlad_blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Post(models.Model):
	author = models.ForeignKey('auth.User', null=True, blank=True)
	title = models.CharField(max_length=250, unique=True)
	slug = models.SlugField(max_length=100, unique=True)
	text = models.TextField()
	created_date = models.DateTimeField(default=timezone.now)
	published_date = models.DateTimeField(blank=True, null=True)
	category = models.ForeignKey('blog.Category', null=True, blank=True)

	def __str__(self):
		return '%s' % self.title

	def __unicode__(self):
		return '%s' % self.title

	@models.permalink
	def get_absolute_url(self):
		return ('blog:post', None, {'slug': self.slug})


class Category(models.Model):
	title = models.CharField(max_length=100, db_index=True)
	slug = models.SlugField(max_length=100, db_index=True)
	logo = models.FileField()

	def __str__(self):
		return '%s' % self.title

	def __unicode__(self):
		return '%s' % self.title

	@models.permalink
	def get_absolute_url(self):
		return('blog:category', None, {'slug': self.slug})

blog/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import redirect
from django.utils import timezone
from .models import Post, Category


class PostListView(ListView):
	template_name = 'blog/index.html'
	context_object_name = 'posts'
	paginate_by = 3

	def get_context_data(self, **kwargs):
		context = super(PostListView, self).get_context_data(**kwargs)
		context['cats'] = Category.objects.all()
		return context

	def get_queryset(self):
		return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')


class PostDetailView(DetailView):
	model = Post
	template_name = 'blog/post.html'


class PostCreateView(CreateView):
	model = Post
	template_name = 'blog/post_add.html'
	fields = ['title', 'slug', 'text', 'published_date', 'category']

	def form_valid(self, form):
		form.instance.author = self.request.user
		form.instance.created_date = timezone.now()
		return super(PostCreateView, self).form_valid(form)

	def dispatch(self, request, *args, **kwargs):
		if (request.user == None) or not (request.user.is_staff):
			return redirect('blog:index')
		return super(PostCreateView, self).dispatch(request, *args, **kwargs)


class PostEditView(UpdateView):
	model = Post
	template_name = 'blog/post_edit.html'
	fields = ['author', 'title', 'slug', 'text', 'published_date', 'category']


class PostDeleteView(DeleteView):
	model = Post
	template_name = 'blog/post_delete.html'
	success_url = reverse_lazy('blog:index')


class CategoryListView(ListView):
	template_name = 'blog/category.html'
	context_object_name = 'posts'
	paginate_by = 5

	def get_context_data(self, **kwargs):
		context = super(CategoryListView, self).get_context_data(**kwargs)
		context['category'] = Category.objects.get(slug = self.kwargs['slug'])
		return context

	def get_queryset(self):
		return Post.objects.filter(published_date__lte=timezone.now()).filter(category__slug=self.kwargs['slug']).order_by('-published_date')

blog/templates/blog/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="ru">
<head>
	<meta>
	<title>{% block title %} Blog {% endblock %}</title>

	<!-- Bootstrap -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	<link href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet">
	
	<!-- Custom styles -->
	<link rel="stylesheet" href="{% static "blog/css/style.css" %}">
</head>
<body>

	<div class="navbar navbar-inverse">
		<div class="container">
			<a class="navbar-brand" href="{% url 'blog:index' %}">Kolitansky</a>
			{% if user.is_authenticated %}
				{% if user.is_staff %}
					<ul class="nav navbar-nav navbar-right">
						<li>
							<a href="{% url 'blog:post-add' %}"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>&nbsp;Написать пост</a>
						</li>
					</ul>
				{% endif %}
			{% else %}
			<ul class="nav navbar-nav navbar-right">
				<li>
					<a href="#">Log in</a>
				</li>
				<li>
					<a href="#">Sign in</a>
				</li>
			</ul>
			{% endif %}
		</div>
	</div>

	{% block main %}

	{% endblock %}

	<footer class="blog-footer">
    	<p>Blog template built for <a href="http://getbootstrap.com">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
    	<p>
    		<a href="#">Back to top</a>
    	</p>
    </footer>
</body>
</html>

blog/templates/blog/category.html
{% extends 'blog/base.html' %}

{% block title %} {{ category.title }} {% endblock %}

{% block main %}
	<div class="container-fluid">
		<div style="background: url({{ category.logo.url }})" class="row category-bg">
			<h1 class="category-title">{{ category.title }}</h1>
		</div>
	</div>
	<div class="container">
		<div class="row">
				
			<div class="col-sm-8 blog-main">
				{% for post in posts %}
					<div class="blog-post">
						<h2 class="blog-post-title"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
						<p class="blog-post-meta">{{ post.published_date }} by <a href="#">{{ post.author }}</a></p>
						<p>
							{{ post.text|linebreaksbr }}
						</p>
					</div>
				{% endfor %}
			</div>

			<div class="col-sm-3 col-sm-offset-1 blog-sidebar">
	          <div class="sidebar-module sidebar-module-inset">
	            <h4>About</h4>
	            <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
	          </div>
	          <div class="sidebar-module">
	            <h4>Elsewhere</h4>
	            <ol class="list-unstyled">
	              <li><a href="#">GitHub</a></li>
	              <li><a href="#">Twitter</a></li>
	              <li><a href="#">Facebook</a></li>
	            </ol>
	          </div>
	        </div><!-- /.blog-sidebar -->

		</div>
	</div>

	
	<!-- TEMP -->
	{% if paginator.num_pages > 1 %}
	<div class="row">
		<div class="col-sm-4 col-sm-offset-4 my-pagination">
			<nav aria-label="Page navigation">
				<ul class="pagination">
					{% if page_obj.has_previous %}
					<li>
				    	<a href="{% url "blog:index" %}?page={{ page_obj.previous_page_number }}" aria-label="Previous">
				    		<span aria-hidden="true">&laquo;</span>
				      	</a>
				    </li>
				    {% else %}
					<li class="disabled">
				    	<a href="#" aria-label="Previous">
				    		<span aria-hidden="true">&laquo;</span>
				      	</a>
				    </li>
					{% endif %}

					{% for pn in paginator.page_range %}
						{% if page_obj.number != pn %}
						<li>
							<a href="{% url "blog:index" %}?page={{ pn }}">
								{{ pn }}
							</a>
						</li>
						{% else %}
						<li class="active">
							<a href="#">{{ pn }}</a>
						</li>
						{% endif %}
					{% endfor %}
					
					{% if page_obj.has_next %}
					<li>
						<a href="{% url "blog:index" %}?page={{ page_obj.next_page_number }}" aria-label="Next">
							<span aria-hidden="true">&raquo;</span>
						</a>
					</li>
					{% else %}
					<li class="disabled">
						<a href="#" aria-label="Next">
							<span aria-hidden="true">&raquo;</span>
						</a>
					</li>
					{% endif %}
					
				</ul>
			</nav>
		</div>
	</div>
	{% endif %}
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block main %}
	<div style="margin-top: 50px;" class="container">
		<div class="row">
				
			<div class="col-sm-8 blog-main">
				{% for post in posts %}
					<div class="blog-post">
						{% if user.is_staff %}
						<div class="post-edit-buttons">
							<a href="{% url "blog:post-edit" slug=post.slug %}">
								<button type="button" class="btn btn-default"><span class="glyphicon glyphicon-pencil"></span></button>
							</a>
							<a href="{% url "blog:post-delete" slug=post.slug %}">
								<button type="button" class="btn btn-default"><span class="glyphicon glyphicon-remove"></span></button>
							</a>
						</div>
						{% endif %}
						<h2 class="blog-post-title"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
						<p class="blog-post-meta">{{ post.published_date }} by <a href="#">{{ post.author }}</a></p>
						<p>
							{{ post.text|linebreaksbr|truncatewords_html:50 }}
						</p>
					</div>
				{% endfor %}
			</div>

			<div class="col-sm-3 col-sm-offset-1 blog-sidebar">
	          <div class="sidebar-module sidebar-module-inset">
	            <h4>About</h4>
	            <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
	          </div>
	          <div class="sidebar-module">
	            <h4>Categories</h4>
	            <ol class="list-unstyled">
	            {% for cat in cats %}
					<li><a href="{{ cat.get_absolute_url }}">{{ cat.title }}</a></li>
	            {% endfor %}
	            </ol>
	          </div>
	          <div class="sidebar-module">
	            <h4>Elsewhere</h4>
	            <ol class="list-unstyled">
	              <li><a href="#">GitHub</a></li>
	              <li><a href="#">Twitter</a></li>
	              <li><a href="#">Facebook</a></li>
	            </ol>
	          </div>
	        </div><!-- /.blog-sidebar -->

		</div>
	</div>

	
	<!-- TEMP -->
	{% if paginator.num_pages > 1 %}
	<div class="row">
		<div class="col-sm-4 col-sm-offset-4 my-pagination">
			<nav aria-label="Page navigation">
				<ul class="pagination">
					{% if page_obj.has_previous %}
					<li>
				    	<a href="{% url "blog:index" %}?page={{ page_obj.previous_page_number }}" aria-label="Previous">
				    		<span aria-hidden="true">&laquo;</span>
				      	</a>
				    </li>
				    {% else %}
					<li class="disabled">
				    	<a href="#" aria-label="Previous">
				    		<span aria-hidden="true">&laquo;</span>
				      	</a>
				    </li>
					{% endif %}

					{% for pn in paginator.page_range %}
						{% if page_obj.number != pn %}
						<li>
							<a href="{% url "blog:index" %}?page={{ pn }}">
								{{ pn }}
							</a>
						</li>
						{% else %}
						<li class="active">
							<a href="#">{{ pn }}</a>
						</li>
						{% endif %}
					{% endfor %}
					
					{% if page_obj.has_next %}
					<li>
						<a href="{% url "blog:index" %}?page={{ page_obj.next_page_number }}" aria-label="Next">
							<span aria-hidden="true">&raquo;</span>
						</a>
					</li>
					{% else %}
					<li class="disabled">
						<a href="#" aria-label="Next">
							<span aria-hidden="true">&raquo;</span>
						</a>
					</li>
					{% endif %}
					
				</ul>
			</nav>
		</div>
	</div>
	{% endif %}

{% endblock %}

blog/templates/blog/post.html
{% extends 'blog/base.html' %}

{% block title %} {{ post.title }} {% endblock %}

{% block main %}
	<div class="container">
		<div class="blog-header">
				<h1 class="blog-title">{{ post.title }}</h1>
	        	<div class="lead blog-description">
			            <p class="blog-post-meta">{{ post.published_date }} by <a href="#">{{ post.author }}</a></p>
	        	</div>
		</div>
		<div class="row">
				
			<div class="col-sm-12 blog-main">
				<div class="blog-post">

					<p>
						{{ post.text|linebreaksbr }}
					</p>

				</div>
			</div>
		</div>
	</div>

{% endblock %}

blog/templates/blog/post_add.html
{% extends 'blog/base.html' %}
{% block title %} Добавить пост {% endblock %}

{% block main %}
<div class="container">
	<form action="" method="post">{% csrf_token %}
	    {{ form.as_p }}
	    <input type="submit" class="btn btn-success" value="Save" />
	</form>
</div>
{% endblock %}

blog/templates/blog/post_delete.html
{% extends 'blog/base.html' %}
{% block title %} Удалить пост {% endblock %}

{% block main %}
<div class="container">
	<form action="" method="post">{% csrf_token %}
	    <p>Are you sure you want to delete "{{ object }}"?</p>
	    <input type="submit" value="Confirm" />
	</form>
</div>
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}
{% block title %} Редактировать пост {% endblock %}

{% block main %}
<div class="container">
	<form action="" method="post">{% csrf_token %}
	    {{ form.as_p }}
	    <input type="submit" class="btn btn-success" value="Update" />
	</form>
</div>
{% endblock %}